// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomePageDocumentDataSlicesSlice = HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TwoColumnGridSlice
  | BlockContentSlice
  | ServiceHeroSlice
  | HeroSectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Project → Project's Gallery*
 */
export interface ProjectPostDocumentDataGalleryImagesItem {
  /**
   * Gallery Image field in *Project → Project's Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Project documents
 */
interface ProjectPostDocumentData {
  /**
   * Client Name field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Client's Name (Must)
   * - **API ID Path**: project_post.client_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client_name: prismic.KeyTextField;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Description (Must)
   * - **API ID Path**: project_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Project Main Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.project_main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_main_image: prismic.ImageField<never>;

  /**
   * Year field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Year (Must)
   * - **API ID Path**: project_post.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  year: prismic.KeyTextField;

  /**
   * Sector field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.sector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sector: prismic.ContentRelationshipField<"sector_post">;

  /**
   * Subsector field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.subsector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subsector: prismic.ContentRelationshipField<"subsector_post">;

  /**
   * Role field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Role (Must)
   * - **API ID Path**: project_post.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  role: prismic.KeyTextField;

  /**
   * Location field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Location (Must)
   * - **API ID Path**: project_post.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Project's Gallery field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.gallery_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery_images: prismic.GroupField<
    Simplify<ProjectPostDocumentDataGalleryImagesItem>
  >;

  /**
   * Next Project field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.next_project
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  next_project: prismic.ContentRelationshipField<"project_post"> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectPostDocumentData>,
    "project_post",
    Lang
  >;

/**
 * Item in *Sector → Related Subsectors*
 */
export interface SectorPostDocumentDataRelatedSubsectorsItem {
  /**
   * Subsector field in *Sector → Related Subsectors*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.related_subsectors[].subsector
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subsector: prismic.ContentRelationshipField<"subsector_post">;
}

/**
 * Content for Sector documents
 */
interface SectorPostDocumentData {
  /**
   * Sector Name field in *Sector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Main Image field in *Sector*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Description field in *Sector*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Related Subsectors field in *Sector*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.related_subsectors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  related_subsectors: prismic.GroupField<
    Simplify<SectorPostDocumentDataRelatedSubsectorsItem>
  > /**
   * Meta Title field in *Sector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sector*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sector_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Sector document from Prismic
 *
 * - **API ID**: `sector_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SectorPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SectorPostDocumentData>,
    "sector_post",
    Lang
  >;

/**
 * Item in *Settings → Main Navigation*
 */
export interface SettingsDocumentDataMainNavigationItem {
  /**
   * Navigation Title field in *Settings → Main Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Products, Who We Are
   * - **API ID Path**: settings.main_navigation[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Navigation Link field in *Settings → Main Navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.main_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField<
    "page" | "sector_post" | "project_post"
  >;

  /**
   * Has Submenu field in *Settings → Main Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.main_navigation[].has_submenu
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_submenu: prismic.BooleanField;
}

/**
 * Item in *Settings → Submenu Sections → Submenu Items*
 */
export interface SettingsDocumentDataSubmenuSectionsItemsItem {
  /**
   * Item Title field in *Settings → Submenu Sections → Submenu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. About Us
   * - **API ID Path**: settings.submenu_sections[].items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Section ID field in *Settings → Submenu Sections → Submenu Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. about-us (for scrolling to section)
   * - **API ID Path**: settings.submenu_sections[].items[].section_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_id: prismic.KeyTextField;

  /**
   * Display Order field in *Settings → Submenu Sections → Submenu Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1, 2, 3...
   * - **API ID Path**: settings.submenu_sections[].items[].order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Item in *Settings → Submenu Sections*
 */
export interface SettingsDocumentDataSubmenuSectionsItem {
  /**
   * Parent Navigation field in *Settings → Submenu Sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter exact navigation title (e.g. Who We Are)
   * - **API ID Path**: settings.submenu_sections[].parent_nav
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  parent_nav: prismic.KeyTextField;

  /**
   * Submenu Items field in *Settings → Submenu Sections*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.submenu_sections[].items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  items: prismic.NestedGroupField<
    Simplify<SettingsDocumentDataSubmenuSectionsItemsItem>
  >;
}

/**
 * Item in *Settings → Featured Sectors in Navigation*
 */
export interface SettingsDocumentDataFeaturedSectorsItem {
  /**
   * Sector field in *Settings → Featured Sectors in Navigation*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.featured_sectors[].sector
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sector: prismic.ContentRelationshipField<"sector_post">;

  /**
   * Display Subsectors field in *Settings → Featured Sectors in Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: settings.featured_sectors[].display_subsectors
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  display_subsectors: prismic.BooleanField;

  /**
   * Display Order field in *Settings → Featured Sectors in Navigation*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 1, 2, 3...
   * - **API ID Path**: settings.featured_sectors[].order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Item in *Settings → Product Categories*
 */
export interface SettingsDocumentDataProductCategoriesItem {
  /**
   * Project field in *Settings → Product Categories*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.product_categories[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project_post">;
}

/**
 * Item in *Settings → Social Media Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Platform Name field in *Settings → Social Media Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Instagram
   * - **API ID Path**: settings.social_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Social Media URL field in *Settings → Social Media Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter full URL
   * - **API ID Path**: settings.social_links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Settings → Contact Information*
 */
export interface SettingsDocumentDataContactInformationItem {
  /**
   * Information Type field in *Settings → Contact Information*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_information[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"email" | "phone" | "address">;

  /**
   * Contact Detail field in *Settings → Contact Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter contact information
   * - **API ID Path**: settings.contact_information[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;

  /**
   * Display Order field in *Settings → Contact Information*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_information[].order
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  order: prismic.NumberField;
}

/**
 * Item in *Settings → Footer Legal Links*
 */
export interface SettingsDocumentDataFooterLegalLinksItem {
  /**
   * Link Text field in *Settings → Footer Legal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Privacy Policy
   * - **API ID Path**: settings.footer_legal_links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Settings → Footer Legal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /privacy
   * - **API ID Path**: settings.footer_legal_links[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter site title
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Main Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.main_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataMainNavigationItem>
  >;

  /**
   * Submenu Sections field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.submenu_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  submenu_sections: prismic.GroupField<
    Simplify<SettingsDocumentDataSubmenuSectionsItem>
  >;

  /**
   * Featured Sectors in Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.featured_sectors[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_sectors: prismic.GroupField<
    Simplify<SettingsDocumentDataFeaturedSectorsItem>
  >;

  /**
   * Product Categories field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.product_categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  product_categories: prismic.GroupField<
    Simplify<SettingsDocumentDataProductCategoriesItem>
  >;

  /**
   * Social Media Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;

  /**
   * Contact Information field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_information[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_information: prismic.GroupField<
    Simplify<SettingsDocumentDataContactInformationItem>
  >;

  /**
   * Footer Tagline field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: MEP Solutions // Firefighting Solutions // Valves // Pipes // Hose Cabinet // Pumps
   * - **API ID Path**: settings.footer_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_tagline: prismic.KeyTextField;

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer Legal Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_legal_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_legal_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterLegalLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Item in *Subsector → Featured Projects*
 */
export interface SubsectorPostDocumentDataFeaturedProjectsItem {
  /**
   * Project field in *Subsector → Featured Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.featured_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project_post">;
}

/**
 * Content for Subsector documents
 */
interface SubsectorPostDocumentData {
  /**
   * Subsector Name field in *Subsector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Main Image field in *Subsector*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Description field in *Subsector*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Parent Sector field in *Subsector*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.parent_sector
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent_sector: prismic.ContentRelationshipField<"sector_post">;

  /**
   * Featured Projects field in *Subsector*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.featured_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  featured_projects: prismic.GroupField<
    Simplify<SubsectorPostDocumentDataFeaturedProjectsItem>
  > /**
   * Meta Title field in *Subsector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Subsector*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Subsector*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: subsector_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Subsector document from Prismic
 *
 * - **API ID**: `subsector_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubsectorPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SubsectorPostDocumentData>,
    "subsector_post",
    Lang
  >;

export type AllDocumentTypes =
  | HomePageDocument
  | PageDocument
  | ProjectPostDocument
  | SectorPostDocument
  | SettingsDocument
  | SubsectorPostDocument;

/**
 * Item in *BlockContent → Default → Primary → Right Paragraphes*
 */
export interface BlockContentSliceDefaultPrimaryRightParagraphesItem {
  /**
   * Paragraph field in *BlockContent → Default → Primary → Right Paragraphes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Paragraph
   * - **API ID Path**: block_content.default.primary.right_paragraphes[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *BlockContent → Default → Primary*
 */
export interface BlockContentSliceDefaultPrimary {
  /**
   * Left Paragraph field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Left Paragraph ( Optional )
   * - **API ID Path**: block_content.default.primary.left_paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  left_paragraph: prismic.KeyTextField;

  /**
   * CTA field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter CTA ( Optional )
   * - **API ID Path**: block_content.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Show CTA field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: block_content.default.primary.show_cta
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_cta: prismic.BooleanField;

  /**
   * Right Paragraphes field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.default.primary.right_paragraphes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  right_paragraphes: prismic.GroupField<
    Simplify<BlockContentSliceDefaultPrimaryRightParagraphesItem>
  >;
}

/**
 * Default variation for BlockContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlockContent*
 */
type BlockContentSliceVariation = BlockContentSliceDefault;

/**
 * BlockContent Shared Slice
 *
 * - **API ID**: `block_content`
 * - **Description**: BlockContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSlice = prismic.SharedSlice<
  "block_content",
  BlockContentSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Hero Slides*
 */
export interface HeroSectionSliceDefaultPrimarySlidesItem {
  /**
   * Background Type field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select background type
   * - **Default Value**: image
   * - **API ID Path**: hero_section.default.primary.slides[].slide_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  slide_type: prismic.SelectField<"image" | "video", "filled">;

  /**
   * Background Image field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.slides[].background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<"mobile">;

  /**
   * Background Video URL field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Enter video URL (MP4)
   * - **API ID Path**: hero_section.default.primary.slides[].background_video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video Poster Image field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.slides[].video_poster
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_poster: prismic.ImageField<never>;

  /**
   * Main Heading field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter main heading
   * - **API ID Path**: hero_section.default.primary.slides[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subheading
   * - **API ID Path**: hero_section.default.primary.slides[].subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * CTA Button Text field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get Started
   * - **API ID Path**: hero_section.default.primary.slides[].cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /contact
   * - **API ID Path**: hero_section.default.primary.slides[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Text Color Theme field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select text color
   * - **Default Value**: light
   * - **API ID Path**: hero_section.default.primary.slides[].text_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  text_color: prismic.SelectField<"light" | "dark", "filled">;

  /**
   * Overlay Opacity (0-100) field in *HeroSection → Default → Primary → Hero Slides*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 40
   * - **API ID Path**: hero_section.default.primary.slides[].overlay_opacity
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  overlay_opacity: prismic.NumberField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Hero Slides field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  slides: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimarySlidesItem>
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero slider with multiple slides
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: Modern hero slider with image/video backgrounds
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *BlockHero → Default → Primary*
 */
export interface ServiceHeroSliceDefaultPrimary {
  /**
   * Service Title field in *BlockHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Service Title ( Must )
   * - **API ID Path**: service_hero.default.primary.service_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_title: prismic.KeyTextField;
}

/**
 * Default variation for BlockHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlockHero*
 */
type ServiceHeroSliceVariation = ServiceHeroSliceDefault;

/**
 * BlockHero Shared Slice
 *
 * - **API ID**: `service_hero`
 * - **Description**: ServiceHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSlice = prismic.SharedSlice<
  "service_hero",
  ServiceHeroSliceVariation
>;

/**
 * Item in *TwoColumnGrid → Default → Primary → Descriptions*
 */
export interface TwoColumnGridSliceDefaultPrimaryDescriptionsItem {
  /**
   * Description field in *TwoColumnGrid → Default → Primary → Descriptions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description text
   * - **API ID Path**: two_column_grid.default.primary.descriptions[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *TwoColumnGrid → Default → Primary → Under Title Descriptions*
 */
export interface TwoColumnGridSliceDefaultPrimaryUnderTitleDescriptionsItem {
  /**
   * Under Title Description field in *TwoColumnGrid → Default → Primary → Under Title Descriptions*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter description text
   * - **API ID Path**: two_column_grid.default.primary.underTitleDescriptions[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *TwoColumnGrid → Default → Primary*
 */
export interface TwoColumnGridSliceDefaultPrimary {
  /**
   * sectionId field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Id
   * - **API ID Path**: two_column_grid.default.primary.sectionid
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sectionid: prismic.KeyTextField;

  /**
   * Title field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section title
   * - **API ID Path**: two_column_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * eyebrow field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Eyebrow ( Must )
   * - **API ID Path**: two_column_grid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Subtitle field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter section subtitle
   * - **API ID Path**: two_column_grid.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Descriptions field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_grid.default.primary.descriptions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  descriptions: prismic.GroupField<
    Simplify<TwoColumnGridSliceDefaultPrimaryDescriptionsItem>
  >;

  /**
   * Under Title Descriptions field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_grid.default.primary.underTitleDescriptions[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  underTitleDescriptions: prismic.GroupField<
    Simplify<TwoColumnGridSliceDefaultPrimaryUnderTitleDescriptionsItem>
  >;

  /**
   * leftImage field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_grid.default.primary.leftimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  leftimage: prismic.ImageField<never>;

  /**
   * rightImage field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_grid.default.primary.rightimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  rightimage: prismic.ImageField<never>;

  /**
   * reverse field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: two_column_grid.default.primary.reverse
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  reverse: prismic.BooleanField;

  /**
   * CTA field in *TwoColumnGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter CTA ( Optional )
   * - **API ID Path**: two_column_grid.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for TwoColumnGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoColumnGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TwoColumnGrid*
 */
type TwoColumnGridSliceVariation = TwoColumnGridSliceDefault;

/**
 * TwoColumnGrid Shared Slice
 *
 * - **API ID**: `two_column_grid`
 * - **Description**: A two-column layout with animated title, subtitle, and descriptions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoColumnGridSlice = prismic.SharedSlice<
  "two_column_grid",
  TwoColumnGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectPostDocument,
      ProjectPostDocumentData,
      ProjectPostDocumentDataGalleryImagesItem,
      SectorPostDocument,
      SectorPostDocumentData,
      SectorPostDocumentDataRelatedSubsectorsItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataMainNavigationItem,
      SettingsDocumentDataSubmenuSectionsItemsItem,
      SettingsDocumentDataSubmenuSectionsItem,
      SettingsDocumentDataFeaturedSectorsItem,
      SettingsDocumentDataProductCategoriesItem,
      SettingsDocumentDataSocialLinksItem,
      SettingsDocumentDataContactInformationItem,
      SettingsDocumentDataFooterLegalLinksItem,
      SubsectorPostDocument,
      SubsectorPostDocumentData,
      SubsectorPostDocumentDataFeaturedProjectsItem,
      AllDocumentTypes,
      BlockContentSlice,
      BlockContentSliceDefaultPrimaryRightParagraphesItem,
      BlockContentSliceDefaultPrimary,
      BlockContentSliceVariation,
      BlockContentSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimarySlidesItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ServiceHeroSlice,
      ServiceHeroSliceDefaultPrimary,
      ServiceHeroSliceVariation,
      ServiceHeroSliceDefault,
      TwoColumnGridSlice,
      TwoColumnGridSliceDefaultPrimaryDescriptionsItem,
      TwoColumnGridSliceDefaultPrimaryUnderTitleDescriptionsItem,
      TwoColumnGridSliceDefaultPrimary,
      TwoColumnGridSliceVariation,
      TwoColumnGridSliceDefault,
    };
  }
}
