import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";
import SmoothScroller from "@/animation/SmoothScrolling";
import Navigation from "@/components/navbar";
import { createClient } from "@/prismicio";
import { SettingsDocumentData } from "../../prismicio-types";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const client = createClient();
const settings = await client.getSingle("settings");


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Navigation settings={settings as unknown as SettingsDocumentData} />
          {children}
          <SmoothScroller />
        </body>
      </html>
    </ViewTransitions>
  );
}
